### ISSUE TITLE
type in 07_PyTorch.ipynb

### ISSUE THREAD

**Issue by thewilsonator** [GokuMohandas/practicalAI#107]
Under **Gradients** the text 
$ y = 3x + 2 $
$ y = \sum{y}/N $
$ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(z)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

should be 

$ y = 3x + 2 $
$ **z** = \sum{y}/N $
$ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(**y**)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

**Comment by GokuMohandas** [comment]
absolutely correct @thewilsonator , I'll make the change!
