### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by zhyongquan** [GokuMohandas/practicalAI#69]
Great repo!
Can i translate it to Chinese?

**Comment by zhyongquan** [comment]
https://github.com/MLEveryday/practicalAI-cn
We have a organization to translate popular machine learning repo.

**Comment by GokuMohandas** [comment]
absolutely, go ahead! Let me know if you need any clarifications, etc.

**Comment by franztao** [comment]
I will translate step by step in my blog (https://franztao.github.io/)  based the https://github.com/MLEveryday/practicalAI-cn
