### ISSUE TITLE
3d or 2d numpy array?

### ISSUE THREAD

**Issue by captDaylight** [GokuMohandas/practicalAI#83]
In the [numpy notebook](https://github.com/GokuMohandas/practicalAI/blob/master/notebooks/02_NumPy.ipynb), in the section `# 3-D array (matrix)` I see that when you run the cell one of the outputs is `x ndim:  2`. Seems that the title is in conflict with how numpy categorizes it and I've always considered `[[], []]` to be 2d.

**Comment by GokuMohandas** [comment]
good catch. I've fixed the confusion
