### ISSUE TITLE
Alternative to Colab and Binder for running `practicalAI` in the cloud

### ISSUE THREAD

**Issue by martinzugnoni** [GokuMohandas/practicalAI#90]
Hi @GokuMohandas,

I've been recently taking a look at the sample Notebooks in this project and I found them really interesting and valuable for teaching purposes. We're even thinking about adding part of them to our curriculum at https://rmotr.com/ (cofounder and teacher here), in our Data Science program.

We have a small service at RMOTR that lets you run a Jupyter environment online in a single click. Similar to Google Colab or Binder, but also with the ability of installing custom requirements, clone an entire GH repo, etc. We use it for our students, so they don't have to hit the initial wall of installing the whole local Jupyter setup when they are getting started in the DS world.

You can see how `practicalAI` looks like in the service using this link:
https://notebooks.rmotr.com/clone/gh/GokuMohandas/practicalAI

Note that all requirements listed in `requirements.txt` are already installed when the env is loaded, so people can start using it right away. That gives you the flexibility of adding any requirement, and not being tied to what Colab provides by default.

Do you think it would be a good choice to add it as a third launching option? Alternatively to Colab and Binder, already listed in the README.

I hope you like it, and I truly appreciate any feedback.

thanks.

**Comment by GokuMohandas** [comment]
Hey @martinzugnoni,

This is very cool stuff! I'll add the button to access rmotr on the README tonight. And keep me posted on adding practicalAI to your curriculum, I'd love to contribute.

**Comment by oxford1223334** [comment]
..

**Comment by martinzugnoni** [comment]
Sounds great, @GokuMohandas! Let me know if there's anything I can help you with.

**Comment by GokuMohandas** [comment]
@martinzugnoni  added the button and played around a bit with rmotr too, very neat platform!

**Comment by martinzugnoni** [comment]
@GokuMohandas sounds great! Let me know if there's anything else we can help with.
