### ISSUE TITLE
alternative for colab notebook service in mainland china

### ISSUE THREAD

**Issue by gerard0315** [GokuMohandas/practicalAI#97]
hi!
appreciate your work here, me and my friends really learned a lot here
we happened to find a platform in mainland China providing similar service to google colab and kaggle ( as you may known there is connectivity problem to google services in mainland China) called KESCI(www.kesci.com). They provide dev-ready and up-to-date Python & R cpu environment all for free and an upcoming gpu support.
we also managed to translate the whole series to Chinese and applied for a column to publish them on KESCI, as a series. you can access it here : https://www.kesci.com/home/column/5c20e4c5916b6200104eea63 
the Computer Vision notebook has already been translated but is still being trained in the transfer-learning section
also, do you think it is possible to add this as another launching option? i think there must be more people in China who could learn from your tutorials!

**Comment by GokuMohandas** [comment]
@gerard0315 added the button and this is such great and quick work on the translation end!

**Comment by gerard0315** [comment]
@GokuMohandas thanks! we'll keep up the work here, but let me know if you need any help!
